#!/usr/bin/env python3
"""
generate_batch_reports.py - 批量生成竞品价格分析报告
支持导出：Markdown / HTML / PDF（需要wkhtmltopdf）

用法:
python scripts/generate_batch_reports.py --input examples/three_hotels.json --output reports/ --api-key YOUR_AMAP_KEY
"""

import os
import json
import argparse
from datetime import datetime
from typing import List, Dict

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core.amap_client import AmapClientWrapper as AmapClient
from core.competitor_filter_v2 import HotelPOI, filter_competitors_v2, FilterConfig, get_config_for_scenario, filter_competitors_grouped, GroupedCompetitors
from algorithm.pricing_advisor import PricingAdvisor, CompetitorData, DemandLevel, PricingRecommendation

# ── 报告模板 ─────────────────────────────────────────────────

MARKDOWN_TEMPLATE = """# {hotel_name} 竞品价格分析报告
**生成时间**: {generated_at}  
**目标日期**: {target_date}  
**酒店位置**: {district} {lat}, {lon}  

## 酒店基础信息

| 项目 | 值 |
|------|-----|
| 品牌 | {brand} |
| 星级 | {star} |
| 平日基准价 | ¥{weekday_price} |
| 搜索范围 | {max_distance_km}km |
| 场景配置 | {scenario} |

## 竞品筛选结果

### 强相关竞品（AI调价分析使用）

{competitor_table}

### 分组市场全景展示

#### 按品牌分组

| 分组 | 数量 |
|------|------|
| 外资品牌竞品 | {count_foreign} |
| 内资品牌竞品 | {count_domestic} |

#### 按价格区间分组（每组最多10家）

| 价格区间 | 数量 |
|----------|------|
| 低于目标 × 0.7（低价位） | {count_price_low} |
| 目标 × 0.7 ~ 1.3（中价位） | {count_price_mid} |
| 高于目标 × 1.3（高价位） | {count_price_high} |

{auto_expand_note}

## 调价建议

**分析基于 {competitor_count} 家强相关有效竞品**

| 策略 | 推荐价格 | 涨幅 |
|------|----------|------|
| 🛡️ 保守 | ¥{price_conservative} | +{rate_conservative:.1f}% |
| ⚖️ 标准 | ¥{price_standard} | +{rate_standard:.1f}% |
| 🚀 激进 | ¥{price_aggressive} | +{rate_aggressive:.1f}% |

**推荐策略**: {strategy_emoji} **{strategy_name}** ¥{price_recommended}  
**置信度**: {confidence}%  
**推荐涨幅**: +{rate_recommended:.1f}%

## 分析依据

{reasoning}

## 关键洞察

{key_insight}

---

*generated by hotel-compete-report v3.4*
"""

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{hotel_name} - 竞品价格分析报告</title>
<script src="https://cdn.tailwindcss.com"></script>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; }}
  .container {{ max-width: 900px; }}
  @media (max-width: 640px) {{
    .container {{ padding: 10px; }}
    table {{ font-size: 0.9em; }}
    th, td {{ padding: 8px 6px !important; }}
  }}
</style>
</head>
<body>
<div class="container mx-auto px-4 py-8">

<!-- 头部 -->
<h1 class="text-3xl font-bold text-gray-800 pb-4 border-b border-gray-200 mb-6">{hotel_name}</h1>

<div class="bg-gray-50 rounded-lg p-4 mb-8">
<p class="mb-1"><strong class="text-gray-700">生成时间:</strong> {generated_at}</p>
<p class="mb-1"><strong class="text-gray-700">目标日期:</strong> {target_date}</p>
<p><strong class="text-gray-700">酒店位置:</strong> {district} {lat}, {lon}</p>
</div>

<!-- 酒店基础信息 -->
<h2 class="text-2xl font-semibold text-gray-700 mt-8 mb-4">酒店基础信息</h2>
<div class="overflow-x-auto">
<table class="min-w-full border border-gray-200 rounded-lg mb-6">
<tbody>
<tr class="border-b border-gray-200"><td class="px-4 py-3 font-medium text-gray-700 bg-gray-50">品牌</td><td class="px-4 py-3 text-gray-800">{brand}</td></tr>
<tr class="border-b border-gray-200"><td class="px-4 py-3 font-medium text-gray-700 bg-gray-50">星级</td><td class="px-4 py-3 text-gray-800">{star}</td></tr>
<tr class="border-b border-gray-200"><td class="px-4 py-3 font-medium text-gray-700 bg-gray-50">平日基准价</td><td class="px-4 py-3 text-gray-800">¥{weekday_price}</td></tr>
<tr class="border-b border-gray-200"><td class="px-4 py-3 font-medium text-gray-700 bg-gray-50">搜索范围</td><td class="px-4 py-3 text-gray-800">{max_distance_km}km</td></tr>
<tr><td class="px-4 py-3 font-medium text-gray-700 bg-gray-50">场景配置</td><td class="px-4 py-3 text-gray-800">{scenario}</td></tr>
</tbody>
</table>
</div>

<!-- 竞品筛选结果 -->
<h2 class="text-2xl font-semibold text-gray-700 mt-8 mb-4">竞品筛选结果</h2>
<h3 class="text-xl font-semibold text-gray-600 mb-3">强相关竞品（AI调价分析使用）</h3>
<div class="overflow-x-auto">
<table class="min-w-full border border-gray-200 rounded-lg mb-6">
<thead>
<tr class="bg-gray-50">
<th class="px-4 py-3 text-left font-medium text-gray-700 border-b border-gray-200">竞品名称</th>
<th class="px-4 py-3 text-left font-medium text-gray-700 border-b border-gray-200">距离</th>
<th class="px-4 py-3 text-left font-medium text-gray-700 border-b border-gray-200">星级</th>
<th class="px-4 py-3 text-left font-medium text-gray-700 border-b border-gray-200">总分</th>
</tr>
</thead>
<tbody>
{competitor_table_html}
</tbody>
</table>
</div>

<!-- 分组展示 -->
<h3 class="text-xl font-semibold text-gray-600 mb-3">分组市场全景展示</h3>

<div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
<!-- 品牌分组 -->
<div class="bg-white border border-gray-200 rounded-lg p-4">
<h4 class="font-semibold text-gray-700 mb-3">按品牌分组</h4>
<table class="w-full">
<tbody>
<tr><td class="py-2 font-medium text-gray-700">外资品牌竞品</td><td class="py-2 text-right text-gray-800">{count_foreign}</td></tr>
<tr><td class="py-2 font-medium text-gray-700">内资品牌竞品</td><td class="py-2 text-right text-gray-800">{count_domestic}</td></tr>
</tbody>
</table>
</div>

<!-- 价格分组 -->
<div class="bg-white border border-gray-200 rounded-lg p-4">
<h4 class="font-semibold text-gray-700 mb-3">按价格区间分组</h4>
<table class="w-full">
<tbody>
<tr><td class="py-2 font-medium text-gray-700">低于目标 × 0.7</td><td class="py-2 text-right text-gray-800">{count_price_low}</td></tr>
<tr><td class="py-2 font-medium text-gray-700">目标 × 0.7 ~ 1.3</td><td class="py-2 text-right text-gray-800">{count_price_mid}</td></tr>
<tr><td class="py-2 font-medium text-gray-700">高于目标 × 1.3</td><td class="py-2 text-right text-gray-800">{count_price_high}</td></tr>
</tbody>
</table>
</div>
</div>

{auto_expand_html}

<!-- 调价建议 -->
<h2 class="text-2xl font-semibold text-gray-700 mt-8 mb-4">调价建议</h2>
<p class="text-gray-600 mb-4"><strong>分析基于 {competitor_count} 家强相关有效竞品</strong></p>

<div class="overflow-x-auto">
<table class="min-w-full border border-gray-200 rounded-lg mb-6">
<thead>
<tr class="bg-gray-50">
<th class="px-4 py-3 text-left font-medium text-gray-700 border-b border-gray-200">策略</th>
<th class="px-4 py-3 text-left font-medium text-gray-700 border-b border-gray-200">推荐价格</th>
<th class="px-4 py-3 text-left font-medium text-gray-700 border-b border-gray-200">涨幅</th>
</tr>
</thead>
<tbody>
<tr class="border-b border-gray-200">
<td class="px-4 py-3 text-gray-800">🛡️ 保守</td>
<td class="px-4 py-3 text-gray-800">¥{price_conservative}</td>
<td class="px-4 py-3 text-gray-800">+{rate_conservative:.1f}%</td>
</tr>
<tr class="border-b border-gray-200">
<td class="px-4 py-3 text-gray-800">⚖️ 标准</td>
<td class="px-4 py-3 text-gray-800">¥{price_standard}</td>
<td class="px-4 py-3 text-gray-800">+{rate_standard:.1f}%</td>
</tr>
<tr>
<td class="px-4 py-3 text-gray-800">🚀 激进</td>
<td class="px-4 py-3 text-gray-800">¥{price_aggressive}</td>
<td class="px-4 py-3 text-gray-800">+{rate_aggressive:.1f}%</td>
</tr>
</tbody>
</table>
</div>

<!-- 推荐策略 -->
<div class="bg-blue-50 border border-blue-200 rounded-lg p-5 mb-6">
<p class="text-lg">
<strong class="text-blue-800">推荐策略</strong>: 
<span class="font-bold text-blue-900">{strategy_emoji} {strategy_name}</span> → 
<span class="text-xl font-bold text-blue-900">¥{price_recommended}</span>
</p>
<p class="mb-0 text-blue-700">
<strong>置信度</strong>: {confidence}% &nbsp; 
<strong>推荐涨幅</strong>: +{rate_recommended:.1f}%
</p>
</div>

<!-- 分析依据 -->
<h2 class="text-2xl font-semibold text-gray-700 mt-8 mb-4">分析依据</h2>
<ul class="list-disc pl-5 space-y-1 text-gray-700 mb-6">
{reasoning_html}
</ul>

<!-- 关键洞察 -->
<h2 class="text-2xl font-semibold text-gray-700 mt-8 mb-4">关键洞察</h2>
<div class="bg-blue-50 border border-blue-100 rounded-lg p-5 mb-8 text-gray-700">
{key_insight}
</div>

<!-- 页脚 -->
<footer class="text-center text-gray-500 text-sm pt-6 border-t border-gray-200">
generated by hotel-compete-report v3.4
</footer>

</div>
</body>
</html>
"""

# ── 报告生成器 ───────────────────────────────────────────────

class ReportGenerator:
    def __init__(self, amap_api_key: str):
        self.amap = AmapClient(amap_api_key)

    def generate_report(self, hotel_info: Dict, output_dir: str) -> Dict:
        """生成单家酒店报告"""
        # 1. 高德POI搜索周边酒店
        lat = hotel_info["lat"]
        lon = hotel_info["lon"]
        radius_km = hotel_info.get("max_distance_km", 5)
        scenario = hotel_info.get("scenario", "default")

        print(f"🔍 搜索 {hotel_info['name']} 周边 {radius_km}km...")
        # 周边搜索关键词"酒店"
        nearby_pois = self.amap.poi_around(
            keywords="酒店",
            location=(lon, lat),
            radius_km=radius_km,
            page_size=50
        )
        # 计算距离并整理
        nearby_hotels = []
        center_lon, center_lat = lon, lat
        for poi in nearby_pois:
            # 计算距离
            if poi.lon and poi.lat:
                from math import radians, sin, cos, sqrt, atan2
                R = 6371
                dlon = radians(poi.lon - center_lon)
                dlat = radians(poi.lat - center_lat)
                a = sin(dlat/2)**2 + cos(radians(center_lat)) * cos(radians(poi.lat)) * sin(dlon/2)**2
                c = 2 * atan2(sqrt(a), sqrt(1-a))
                distance_km = R * c
                poi.distance_km = distance_km
                nearby_hotels.append(poi)
        # 按距离排序
        nearby_hotels.sort(key=lambda x: x.distance_km if x.distance_km else 999)
        print(f"   找到 {len(nearby_hotels)} 家酒店")

        # 2. 转换为HotelPOI对象
        target = HotelPOI(
            name=hotel_info["name"],
            location=f"{lon},{lat}",
            star=hotel_info["star"],
            brand=hotel_info["brand"],
            price=hotel_info["weekday_price"]
        )

        candidates = []
        for h in nearby_hotels:
            # 排除自己（名称完全匹配排除，部分匹配保留）
            if h.name.strip() != hotel_info["name"].strip():
                poi = HotelPOI(
                    name=h.name,
                    location=f"{h.lon},{h.lat}",
                    star=h.type if h.type else "高档型",
                    brand=self._extract_brand(h.name),
                    distance_km=h.distance_km
                )
                candidates.append(poi)
        print(f"   排除自身后剩余 {len(candidates)} 家候选")

        # 3. v2.1分组筛选
        from core.competitor_filter_v2 import get_config_for_scenario, FilterConfig, filter_competitors_grouped, GroupedCompetitors
        config = get_config_for_scenario(scenario) if scenario != "default" else FilterConfig()
        grouped = filter_competitors_grouped(candidates, target, hotel_info["weekday_price"], config=config)
        filtered_scores = grouped.strong_relevant

        print(f"   筛选出 {len(filtered_scores)} 家强相关有效竞品")

        # 4. 准备竞品数据给调价算法
        # 这里假设：竞品平日价 = 当前价格，假日价 = 平日价 * (1 + 平均涨幅估算)
        # 实际生产环境应该从飞猪API获取真实假日价
        competitor_data = []
        for s in filtered_scores[:8]:  # 取Top 8
            # 简化：假设假日平均涨幅50%（实际应从API获取）
            est_holiday = s.hotel.price * 1.5 if s.hotel.price else hotel_info["weekday_price"] * 1.5
            cd = CompetitorData(
                name=s.hotel.name,
                base_price=s.hotel.price if s.hotel.price else hotel_info["weekday_price"],
                holiday_price=est_holiday,
                star=s.hotel.star,
                brand=s.hotel.brand,
                distance_km=s.hotel.distance_km if s.hotel.distance_km else 0
            )
            competitor_data.append(cd)

        # 5. 调价分析
        # 五一假期，需求高
        demand = DemandLevel.HIGH
        if "weekday" in hotel_info["target_date"].lower():
            demand = DemandLevel.LOW
        elif "weekend" in hotel_info["target_date"].lower():
            demand = DemandLevel.MEDIUM

        advisor = PricingAdvisor(
            base_price=hotel_info["weekday_price"],
            competitors=competitor_data,
            demand_level=demand,
            target_date=hotel_info["target_date"]
        )
        recommendation = advisor.analyze()

        # 6. 生成markdown 和 html
        markdown = self._render_markdown(hotel_info, recommendation, grouped)
        html = self._render_html(hotel_info, recommendation, grouped)

        # 7. 按日期保存
        date_str = hotel_info["target_date"]
        hotel_slug = self._slugify(hotel_info["name"])
        base_name = f"{hotel_slug}-{date_str}"
        hotel_output_dir = os.path.join(output_dir, hotel_slug)
        os.makedirs(hotel_output_dir, exist_ok=True)

        md_path = os.path.join(hotel_output_dir, f"{base_name}.md")
        html_path = os.path.join(hotel_output_dir, f"{base_name}.html")

        with open(md_path, "w", encoding="utf-8") as f:
            f.write(markdown)
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)

        # 更新latest软链接
        latest_md = os.path.join(hotel_output_dir, f"{hotel_slug}-latest.md")
        latest_html = os.path.join(hotel_output_dir, f"{hotel_slug}-latest.html")
        try:
            os.remove(latest_md) if os.path.exists(latest_md) else None
            os.remove(latest_html) if os.path.exists(latest_html) else None
            os.symlink(f"{base_name}.md", latest_md)
            os.symlink(f"{base_name}.html", latest_html)
        except Exception:
            # Windows不支持软链接，跳过
            pass

        print(f"\n✅ 报告生成完成！")
        print(f"   Markdown: {md_path}")
        print(f"   HTML: {html_path}")
        print(f"   Latest: {latest_html}")

        # 更新根索引
        update_root_index(output_dir, hotel_info["name"], hotel_slug, date_str, recommendation)

        return {
            "hotel": hotel_info["name"],
            "markdown": md_path,
            "html": html_path,
            "competitor_count": len(filtered_scores),
            "recommendation": recommendation
        }

    def _extract_brand(self, name: str) -> str:
        """从酒店名提取品牌"""
        brands = ["开元", "洲际", "万豪", "希尔顿", "皇冠假日", "万丽", "香格里拉", "凯悦", "君悦", "威斯汀"]
        for b in brands:
            if b in name:
                return b
        return ""

    def _render_markdown(self, hotel_info: Dict, rec: PricingRecommendation, grouped: GroupedCompetitors) -> str:
        # 竞品表格 - 强相关竞品
        competitor_rows = []
        competitor_rows.append("| 竞品名称 | 距离 | 星级 | 总分 |")
        competitor_rows.append("|----------|------|------|------|")
        for s in grouped.strong_relevant:
            dist = f"{s.hotel.distance_km:.1f}km" if s.hotel.distance_km else "N/A"
            competitor_rows.append(f"| {s.hotel.name} | {dist} | {s.hotel.star} | {s.total_score:.1f} |")
        competitor_table = "\n".join(competitor_rows)

        # 分组统计
        count_foreign = len(grouped.foreign_brands)
        count_domestic = len(grouped.domestic_brands)
        count_price_low = len(grouped.by_price_tier.get("low", []))
        count_price_mid = len(grouped.by_price_tier.get("mid", []))
        count_price_high = len(grouped.by_price_tier.get("high", []))

        auto_expand_note = ""
        if grouped.auto_expanded:
            auto_expand_note = "\n> ℹ️ 初始半径竞品太少，已自动扩展搜索半径\n"

        # 替代方案
        alt = {a["strategy"]: a for a in rec.alternatives}
        cons = alt.get("conservative", {})
        std = alt.get("standard", {})
        agg = alt.get("aggressive", {})

        #  reasoning
        reasoning_list = "\n".join([f"- {r}" for r in rec.reasoning])

        # 关键洞察
        if rec.cpi_score > 120:
            insight = f"目标酒店CPI={rec.cpi_score:.1f}，当前定位高于竞品平均，可以考虑{rec.strategy.value}策略追求更高收益。"
        elif rec.cpi_score > 90:
            insight = f"目标酒店CPI={rec.cpi_score:.1f}，定位与竞品平均相当，标准策略性价比最佳。"
        else:
            insight = f"目标酒店CPI={rec.cpi_score:.1f}，当前价格低于竞品平均，维持性价比定位。"

        return MARKDOWN_TEMPLATE.format(
            hotel_name=hotel_info["name"],
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            target_date=hotel_info["target_date"],
            district=hotel_info.get("district", ""),
            lat=hotel_info["lat"],
            lon=hotel_info["lon"],
            brand=hotel_info["brand"],
            star=hotel_info["star"],
            weekday_price=hotel_info["weekday_price"],
            max_distance_km=hotel_info.get("max_distance_km", 5),
            scenario=hotel_info.get("scenario", "default"),
            competitor_table=competitor_table,
            count_foreign=count_foreign,
            count_domestic=count_domestic,
            count_price_low=count_price_low,
            count_price_mid=count_price_mid,
            count_price_high=count_price_high,
            auto_expand_note=auto_expand_note,
            competitor_count=len(grouped.strong_relevant),
            price_conservative=cons.get("price", 0),
            rate_conservative=cons.get("rate", 0),
            price_standard=std.get("price", 0),
            rate_standard=std.get("rate", 0),
            price_aggressive=agg.get("price", 0),
            rate_aggressive=agg.get("rate", 0),
            strategy_emoji=self._strategy_emoji(rec.strategy),
            strategy_name=rec.strategy.value,
            price_recommended=rec.recommended_price,
            rate_recommended=rec.rate,
            confidence=rec.confidence,
            reasoning=reasoning_list,
            key_insight=insight
        )

    def _render_html(self, hotel_info: Dict, rec: PricingRecommendation, grouped: GroupedCompetitors) -> str:
        # 竞品表格HTML - 强相关竞品
        competitor_rows = []
        for s in grouped.strong_relevant:
            dist = f"{s.hotel.distance_km:.1f}km" if s.hotel.distance_km else "N/A"
            competitor_rows.append(f'<tr class="border-b border-gray-200"><td class="px-4 py-3 text-gray-800">{s.hotel.name}</td><td class="px-4 py-3 text-gray-800">{dist}</td><td class="px-4 py-3 text-gray-800">{s.hotel.star}</td><td class="px-4 py-3 text-gray-800">{s.total_score:.1f}</td></tr>')
        competitor_table_html = "\n".join(competitor_rows)

        # 分组统计
        count_foreign = len(grouped.foreign_brands)
        count_domestic = len(grouped.domestic_brands)
        count_price_low = len(grouped.by_price_tier.get("low", []))
        count_price_mid = len(grouped.by_price_tier.get("mid", []))
        count_price_high = len(grouped.by_price_tier.get("high", []))

        auto_expand_html = ""
        if grouped.auto_expanded:
            auto_expand_html = '<p class="text-gray-600 italic mt-2">ℹ️ 初始半径竞品太少，已自动扩展搜索半径</p>'

        # 替代方案
        alt = {a["strategy"]: a for a in rec.alternatives}
        cons = alt.get("conservative", {})
        std = alt.get("standard", {})
        agg = alt.get("aggressive", {})

        # reasoning
        reasoning_items = "\n".join([f"<li>{r}</li>" for r in rec.reasoning])
        reasoning_html = reasoning_items

        # 关键洞察
        if rec.cpi_score > 120:
            insight = f"目标酒店CPI={rec.cpi_score:.1f}，当前定位高于竞品平均，可以考虑{rec.strategy.value}策略追求更高收益。"
        elif rec.cpi_score > 90:
            insight = f"目标酒店CPI={rec.cpi_score:.1f}，定位与竞品平均相当，标准策略性价比最佳。"
        else:
            insight = f"目标酒店CPI={rec.cpi_score:.1f}，当前价格低于竞品平均，维持性价比定位。"

        return HTML_TEMPLATE.format(
            hotel_name=hotel_info["name"],
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            target_date=hotel_info["target_date"],
            district=hotel_info.get("district", ""),
            lat=hotel_info["lat"],
            lon=hotel_info["lon"],
            brand=hotel_info["brand"],
            star=hotel_info["star"],
            weekday_price=hotel_info["weekday_price"],
            max_distance_km=hotel_info.get("max_distance_km", 5),
            scenario=hotel_info.get("scenario", "default"),
            competitor_table_html=competitor_table_html,
            count_foreign=count_foreign,
            count_domestic=count_domestic,
            count_price_low=count_price_low,
            count_price_mid=count_price_mid,
            count_price_high=count_price_high,
            auto_expand_html=auto_expand_html,
            competitor_count=len(grouped.strong_relevant),
            price_conservative=cons.get("price", 0),
            rate_conservative=cons.get("rate", 0),
            price_standard=std.get("price", 0),
            rate_standard=std.get("rate", 0),
            price_aggressive=agg.get("price", 0),
            rate_aggressive=agg.get("rate", 0),
            strategy_emoji=self._strategy_emoji(rec.strategy),
            strategy_name=rec.strategy.value,
            price_recommended=rec.recommended_price,
            rate_recommended=rec.rate,
            confidence=rec.confidence,
            reasoning_html=reasoning_html,
            key_insight=insight
        )

    def _strategy_emoji(self, strategy):
        emoji_map = {
            "conservative": "🛡️",
            "standard": "⚖️",
            "aggressive": "🚀",
            "premium": "💎",
        }
        return emoji_map.get(strategy.value, "📊")

    def _slugify(self, s: str) -> str:
        return s.replace(" ", "-").replace("大酒店", "").replace("酒店", "").lower()


def update_root_index(output_root: str, hotel_name: str, hotel_slug: str, date_str: str, rec):
    """更新根目录索引"""
    index_path = os.path.join(output_root, "README.md")
    entries = []

    # 如果已有索引，读取旧条目
    if os.path.exists(index_path):
        with open(index_path, "r", encoding="utf-8") as f:
            lines = f.readlines()
            header_done = False
            for line in lines:
                if line.startswith("| "):
                    entries.append(line)
                if not header_done and "| --------" in line:
                    header_done = True

    # 去重（同酒店保留最新）
    entries = [e for e in entries if hotel_name not in e]
    # 新条目
    rel_md_path = f"{hotel_slug}/{hotel_slug}-{date_str}.md"
    rel_html_path = f"{hotel_slug}/{hotel_slug}-{date_str}.html"
    price = rec.recommended_price
    new_entry = f"| [{hotel_name}]({rel_md_path}) | [HTML]({rel_html_path}) | {date_str} | ¥{price} |\n"
    entries.insert(0, new_entry)

    # 写入
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(f"# 酒店竞品价格监测报告\n\n")
        f.write(f"**最后更新**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write("## 报告列表\n\n")
        f.write("| 酒店名称 | HTML最新 | 生成日期 | 推荐价格 |\n")
        f.write("| -------- | -------- | -------- | -------- |\n")
        f.writelines(entries)


def main():
    parser = argparse.ArgumentParser(description="批量生成竞品价格分析报告")
    parser.add_argument("--input", "-i", required=True, help="输入JSON文件")
    parser.add_argument("--output", "-o", required=True, help="输出目录")
    parser.add_argument("--api-key", "-k", required=True, help="高德地图API Key")
    args = parser.parse_args()

    # 创建输出目录
    os.makedirs(args.output, exist_ok=True)

    # 读取输入
    with open(args.input, "r", encoding="utf-8") as f:
        data = json.load(f)

    generator = ReportGenerator(args.api_key)

    results = []
    for hotel in data["hotels"]:
        print(f"\n{'='*60}")
        result = generator.generate_report(hotel, args.output)
        results.append(result)
        print(f"{'='*60}")

    print(f"\n✅ 全部完成！共生成 {len(results)} 份报告")
    for r in results:
        print(f"   {r['hotel']}: {r['markdown']}")

    # 索引已经在generate_report里更新了


if __name__ == "__main__":
    main()
