#!/usr/bin/env python3
"""
travel_assistant.py - 出行AI伴侣 v2.0
升级：整合flyai机票/火车票查询，成为完整出行规划助手

功能：
1. 基于酒店位置，自然语言关键字查询周边设施：
   - 周边美食推荐
   - 最近地铁站/公交站
   - 附近有哪些银行/ATM
   - 周边景区景点
   - 综合出行配套报告

2. 整合flyai MCP查询：
   - 机票查询
   - 火车票查询
   - 酒店查询

用法:
# 周边查询
python scripts/travel_assistant.py --hotel "天津瑞湾开元名都" --lat 39.021567 --lon 117.745689 --query "周边有什么好吃的"

# 机票查询
python scripts/travel_assistant.py --query "北京到上海 明天机票"

# 火车票查询
python scripts/travel_assistant.py --query "天津到上海 2026-05-01 火车票"
"""

import argparse
import json
import os
import sys
import subprocess
from datetime import datetime, timedelta
from typing import List, Dict, Optional, Tuple

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from industry_search.multi_industry import MultiIndustrySearcher, INDUSTRY_CATEGORIES
from core.data_cache import DataCache, get_default_cache

# ── 关键词映射 ─────────────────────────────────────────────

KEYWORD_MAPPING = {
    # 美食相关
    "好吃": ["餐饮"],
    "美食": ["餐饮"],
    "吃饭": ["餐饮"],
    "餐厅": ["餐饮"],
    "火锅": ["餐饮"],
    "烧烤": ["餐饮"],
    # 交通出行周边
    "地铁": ["出行"],
    "地铁站": ["出行"],
    "公交": ["出行"],
    "火车站周边": ["出行"],
    "机场周边": ["出行"],
    "交通": ["出行"],
    # 购物
    "购物": ["购物"],
    "商场": ["购物"],
    "超市": ["购物"],
    # 金融
    "银行": ["金融"],
    "ATM": ["金融"],
    "取钱": ["金融"],
    # 景点
    "景点": ["景区"],
    "景区": ["景区"],
    "公园": ["景区"],
    "玩": ["景区"],
    # 医疗
    "医院": ["医疗"],
    "药店": ["医疗"],
    # 全部
    "全部": list(INDUSTRY_CATEGORIES.keys()),
    "所有": list(INDUSTRY_CATEGORIES.keys()),
    "配套": list(INDUSTRY_CATEGORIES.keys()),
    "综合": list(INDUSTRY_CATEGORIES.keys()),
}


class TravelAssistant:
    """出行AI伴侣 - 基于酒店位置的周边查询助手"""

    def __init__(self, amap_api_key: str):
        self.searcher = MultiIndustrySearcher(api_key=amap_api_key)

    def set_hotel(self, name: str, lat: float, lon: float):
        """设置目标酒店"""
        self.searcher.set_hotel_location(name, (lon, lat))

    def parse_keyword_query(self, query: str) -> List[str]:
        """解析自然语言关键词，返回需要查询的分类"""
        categories = []
        query = query.lower()

        for keyword, cats in KEYWORD_MAPPING.items():
            if keyword in query:
                for cat in cats:
                    if cat not in categories:
                        categories.append(cat)

        if not categories:
            # 默认查餐饮+出行
            return ["餐饮", "出行"]

        return categories

    def generate_markdown_report(self, query: str, radius_km: float = 5.0) -> str:
        """生成Markdown格式出行报告"""
        categories = self.parse_keyword_query(query)
        report = self.searcher.generate_report(categories, radius_km=radius_km)

        lines = []
        lines.append(f"# 🧳 {self.searcher.hotel_name} - 出行配套查询")
        lines.append(f"**查询关键词**: {query}  \n")
        lines.append(f"**搜索范围**: {radius_km}km  \n")

        for cat, r in report["categories"].items():
            cfg = INDUSTRY_CATEGORIES[cat]
            icon = cfg["icon"]
            lines.append(f"\n## {icon} {cat} - {cfg['description']}")
            lines.append(f"- **总数**: {r.total_count}家")
            lines.append(f"- **3km内**: {r.nearby_count}家")
            lines.append(f"- **完善度**: {r.coverage_score}/100")
            if r.nearest:
                d = r.nearest.distance_km
                lines.append(f"- **最近**: {r.nearest.name} ({d:.1f}km)")
            # 列出前5家
            if r.all_pois:
                lines.append("\n近邻推荐:")
                for i, p in enumerate(r.all_pois[:5]):
                    d = p.distance_km
                    lines.append(f"  {i+1}. {p.name} ({d:.1f}km)")

        lines.append(f"\n---\n*generated by hotel-compete-report travel assistant*")
        return "\n".join(lines)


# ── 机票/火车票查询 ───────────────────────────────────────────

def run_flyai_cmd(cmd: str, cache_key: tuple = None, force_refresh: bool = False):
    """执行flyai命令，带缓存"""
    from core.data_cache import DataCache, get_default_cache

    if cache_key is not None and not force_refresh:
        cache = get_default_cache()
        cached = cache.get(*cache_key)
        if cached is not None:
            return cached

    try:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, timeout=60
        )
        if result.returncode == 0 and result.stdout.strip():
            data = json.loads(result.stdout.strip())
            if cache_key is not None:
                cache = get_default_cache()
                cache.set(*cache_key, data)
            return data
        else:
            return None
    except Exception:
        return None


def parse_travel_query(query: str) -> Tuple[Optional[str], Optional[str], Optional[str], str]:
    """
    解析出行查询，识别出发地/目的地/日期/类型

    返回: (from, to, date, type)
    type: "flight" | "train" | "hotel" | "周边"

    支持两种格式:
    1. 北京到上海 明天机票 （标准格式）
    2. 重庆 开元名都 酒店 （酒店搜索：目的地+关键词）→ from_city=重庆, to_city=开元名都
    """
    query = query.lower()

    # 判断类型
    is_flight = any(k in query for k in ["机票", "飞机", "航班"])
    is_train = any(k in query for k in ["火车", "高铁", "动车", "火车票"])
    is_hotel = any(k in query for k in ["酒店", "住宿"])

    # 提取日期
    today = datetime.now()
    date = (today + timedelta(days=1)).strftime("%Y-%m-%d")  # 默认明天

    # 简单正则匹配日期
    import re
    date_match = re.search(r'(202\d-\d\d-\d\d)', query)
    if date_match:
        date = date_match.group(1)

    # 提取出发地 目的地
    # 匹配 "X到Y" 或 "X去Y"
    m = re.search(r'([\u4e00-\u9fa5]{1,15})(到|去)([\u4e00-\u9fa5]{1,15})', query)
    if m:
        from_city = m.group(1).strip()
        to_city = m.group(3).strip()
    elif is_hotel:
        # 酒店搜索特殊格式: "重庆 开元名都 2026-04-23 酒店"
        # → 目的地 = 第一个词，关键词 = 第二个词
        words = [w.strip() for w in query.split() if w.strip() and not w in ["酒店", "住宿"]]
        if len(words) >= 2:
            from_city = words[0]  # 目的地城市
            to_city = " ".join(words[1:-1]) if date_match else " ".join(words[1:])  # 酒店名称
        else:
            from_city = words[0] if words else None
            to_city = None
    else:
        from_city = None
        to_city = None

    if is_flight:
        return (from_city, to_city, date, "flight")
    elif is_train:
        return (from_city, to_city, date, "train")
    elif is_hotel:
        return (from_city, to_city, date, "hotel")
    else:
        # 默认周边查询
        return (None, None, None, "周边")


def search_flight(from_city: str, to_city: str, date: str, force_refresh=False):
    """搜索机票"""
    cmd = f'flyai search-flight --from {from_city} --to {to_city} --date {date}'
    cache_key = ("flight", from_city, to_city, date)
    return run_flyai_cmd(cmd, cache_key, force_refresh)


def search_train(from_city: str, to_city: str, date: str, force_refresh=False):
    """搜索火车票"""
    cmd = f'flyai search-train --from {from_city} --to {to_city} --date {date}'
    cache_key = ("train", from_city, to_city, date)
    return run_flyai_cmd(cmd, cache_key, force_refresh)


def search_hotel(dest: str, keyword: str, check_in: str, check_out: str, force_refresh=False):
    """搜索酒店"""
    cmd = f'flyai search-hotel --dest-name "{dest}" --key-words "{keyword}" --check-in-date {check_in} --check-out-date {check_out}'
    cache_key = ("hotel", dest, keyword, check_in, check_out)
    return run_flyai_cmd(cmd, cache_key, force_refresh)


def format_flight_result(data):
    """格式化机票结果为Markdown，包含预订链接"""
    if not data or data.get("status") != 0:
        return "❌ 未查询到机票数据\n"

    flights = data.get("data", {}).get("flightList", [])
    if not flights:
        return "❌ 未找到航班\n"

    lines = []
    lines.append("## ✈️ 机票搜索结果\n")
    lines.append(f"| 航班 | 出发 | 到达 | 价格 | 航空公司 | 预订链接 |\n")
    lines.append(f"|------|------|------|------|----------|----------|\n")

    for f in flights[:10]:  # 只显示前10个
        name = f.get("flightName", "未知")
        dep = f.get("departTime", "-")
        arr = f.get("arriveTime", "-")
        price = f.get("price", "-")
        airline = f.get("airlineName", "-")
        detail_url = f.get("detailUrl", "")
        if detail_url:
            link = f"[预订]({detail_url})"
        else:
            link = "-"
        lines.append(f"| {name} | {dep} | {arr} | ¥{price} | {airline} | {link} |\n")

    lines.append(f"\n*共 {len(flights)} 个航班，显示前 10 个*")
    lines.append("\n💡 点击预订链接可直接跳转到飞猪预订页面")
    return "".join(lines)


def format_train_result(data):
    """格式化火车票结果为Markdown，包含预订链接"""
    if not data or data.get("status") != 0:
        return "❌ 未查询到火车票数据\n"

    trains = data.get("data", {}).get("trainList", [])
    if not trains:
        return "❌ 未找到火车\n"

    lines = []
    lines.append("## 🚄 火车票搜索结果\n")
    lines.append(f"| 车次 | 出发 | 到达 | 历时 | 硬座 | 二等座 | 一等座 | 预订 |\n")
    lines.append(f"|------|------|------|------|------|--------|--------|------|\n")

    for t in trains[:10]:
        name = t.get("trainName", "未知")
        dep = t.get("departTime", "-")
        arr = t.get("arriveTime", "-")
        duration = t.get("duration", "-")
        yz = t.get("yzPrice", "-")
        ed = t.get("erPrice", "-")
        yd = t.get("ydPrice", "-")
        detail_url = t.get("detailUrl", "")
        if detail_url:
            link = f"[购票]({detail_url})"
        else:
            link = "-"
        lines.append(f"| {name} | {dep} | {arr} | {duration} | ¥{yz} | ¥{ed} | ¥{yd} | {link} |\n")

    lines.append(f"\n*共 {len(trains)} 个车次，显示前 10 个*")
    lines.append("\n💡 点击购票链接可直接跳转到飞猪购票页面")
    return "".join(lines)


def format_hotel_result(data, dest_name: str, check_in: str, check_out: str):
    """格式化酒店搜索结果为Markdown，包含预订链接

    飞猪返回的detailUrl本身就是可直接跳转的预订链接
    """
    if not data or data.get("status") != 0:
        return "❌ 未查询到酒店数据\n"

    hotels = data.get("data", {}).get("itemList", [])
    if not hotels:
        return "❌ 未找到酒店\n"

    lines = []
    lines.append(f"## 🏨 酒店搜索结果\n")
    lines.append(f"**目的地**: {dest_name}  **入住**: {check_in} **退房**: {check_out}\n")
    lines.append(f"| 酒店名称 | 星级 | 价格 | 预订 |\n")
    lines.append(f"|----------|------|------|------|\n")

    for h in hotels[:8]:
        name = h.get("name", "未知")
        star = h.get("star", "-")
        price = h.get("price", "-")
        detail_url = h.get("detailUrl", "")
        if detail_url:
            # flyai 返回的 detailUrl 本身就是飞猪的直接预订链接
            link = f"[预订]({detail_url})"
        else:
            link = "-"
        lines.append(f"| {name} | {star} | ¥{price} | {link} |\n")

    lines.append(f"\n*共 {len(hotels)} 家酒店，显示前 8 个*")
    lines.append("\n💡 点击预订链接可直接跳转到飞猪预订页面，登录后即可下单")
    return "".join(lines)

    def generate_html_report(self, query: str, radius_km: float = 5.0) -> str:
        """生成HTML格式出行报告（手机友好）"""
        categories = self.parse_keyword_query(query)
        report = self.searcher.generate_report(categories, radius_km=radius_km)

        html = []
        html.append("<!DOCTYPE html><html><head>")
        html.append("<meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>")
        html.append("<title>%s - 出行配套查询</title>" % self.searcher.hotel_name)
        html.append("<style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:800px;margin:0 auto;padding:15px;line-height:1.6}h1{color:#2c3e50;border-bottom:2px solid #eee;padding-bottom:10px}.category{background:#f8f9fa;border-radius:8px;padding:15px;margin:15px 0}.poi-item{padding:5px 0;border-bottom:1px solid #eee}.poi-distance{color:#666;font-size:0.9em}</style>")
        html.append("</head><body>")
        html.append("<h1>🧳 %s - 出行配套查询</h1>" % self.searcher.hotel_name)
        html.append("<p><strong>查询关键词:</strong> %s<br><strong>搜索范围:</strong> %gkm</p>" % (query, radius_km))

        for cat, r in report["categories"].items():
            cfg = INDUSTRY_CATEGORIES[cat]
            icon = cfg["icon"]
            html.append(f'<div class="category">')
            html.append(f'<h3>{icon} {cat} - {cfg["description"]}</h3>')
            html.append(f'<p>总数: {r.total_count}家<br>3km内: {r.nearby_count}家<br>完善度: {r.coverage_score}/100</p>')
            if r.nearest:
                d = r.nearest.distance_km
                html.append(f'<p><strong>最近:</strong> {r.nearest.name} ({d:.1f}km)</p>')
            if r.all_pois:
                html.append('<p><strong>推荐:</strong></p>')
                for i, p in enumerate(r.all_pois[:5]):
                    d = p.distance_km
                    html.append(f'<div class="poi-item">{i+1}. {p.name} <span class="poi-distance">({d:.1f}km)</span></div>')
            html.append('</div>')

        html.append("</body></html>")
        return "\n".join(html)


def main():
    parser = argparse.ArgumentParser(description="出行AI伴侣 v2.0 - 酒店周边查询 + 机票/火车票搜索")
    parser.add_argument("--hotel", "-n", help="酒店名称（周边查询需要）")
    parser.add_argument("--lat", type=float, help="纬度（周边查询需要）")
    parser.add_argument("--lon", type=float, help="经度（周边查询需要）")
    parser.add_argument("--query", "-q", required=True, help="查询内容")
    parser.add_argument("--radius", "-r", type=float, default=5.0, help="搜索半径km")
    parser.add_argument("--output-dir", "-o", default="./travel_reports", help="输出目录")
    parser.add_argument("--api-key", "-k", help="高德API Key")
    parser.add_argument("--force-refresh", action="store_true", help="强制刷新缓存")
    args = parser.parse_args()

    # 解析查询类型
    from_city, to_city, date, query_type = parse_travel_query(args.query)

    # 机票/火车票/酒店查询
    if query_type in ["flight", "train", "hotel"]:
        if not from_city or not to_city:
            print("❌ 无法识别出发地和目的地，请使用格式: 北京到上海 明天机票")
            return

        force_refresh = args.force_refresh
        md = []
        md.append(f"# 🧳 出行查询: {args.query}")
        md.append(f"**查询时间**: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")

        if query_type == "flight":
            print(f"[INFO] 正在搜索机票: {from_city} → {to_city}, {date}")
            data = search_flight(from_city, to_city, date, force_refresh)
            md.append(format_flight_result(data))

        elif query_type == "train":
            print(f"[INFO] 正在搜索火车票: {from_city} → {to_city}, {date}")
            data = search_train(from_city, to_city, date, force_refresh)
            md.append(format_train_result(data))

        elif query_type == "hotel":
            # 酒店搜索，默认入住一天
            check_in = date
            check_out = (datetime.strptime(date, "%Y-%m-%d") + timedelta(days=1)).strftime("%Y-%m-%d")
            print(f"[INFO] 正在搜索酒店: {from_city}, {check_in} ~ {check_out}")
            data = search_hotel(from_city, to_city, check_in, check_out, force_refresh)
            md.append(format_hotel_result(data, f"{from_city} {to_city}", check_in, check_out))

        md_content = "\n".join(md)

        # 输出
        os.makedirs(args.output_dir, exist_ok=True)
        from slugify import slugify
        query_slug = args.query[:30].replace(" ", "-").lower()
        md_path = os.path.join(args.output_dir, f"travel-{query_slug}.md")
        html_path = os.path.join(args.output_dir, f"travel-{query_slug}.html")

        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        # 简单HTML
        html_content = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>出行查询 {args.query}</title>
<style>body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:800px;margin:0 auto;padding:15px;}} table{{border-collapse:collapse;width:100%;}} th{{background:#0066cc;color:white;padding:8px;text-align:left;}} td{{padding:6px;border-bottom:1px solid #eee;}}</style>
</head>
<body>
{md_content.replace('\n', '<br>')}
</body>
</html>"""
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        print(f"\n✅ 查询完成!")
        print(f"   Markdown: {md_path}")
        print(f"   HTML: {html_path}")
        print(f"\n📝 预览:\n{'='*60}\n{md_content}")
        return

    # 周边查询（原有功能）
    if args.hotel is None or args.lat is None or args.lon is None:
        print("❌ 周边查询需要提供 --hotel, --lat, --lon 参数")
        print("   机票/火车票查询: 直接 --query \"北京到上海明天机票\" 即可")
        return

    api_key = args.api_key or os.environ.get("AMAP_MAPS_API_KEY", "0f9da10a87fa96c564f2d3d0f459fd6f")

    assistant = TravelAssistant(api_key)
    assistant.set_hotel(args.hotel, args.lat, args.lon)

    md = assistant.generate_markdown_report(args.query, args.radius)
    html = assistant.generate_html_report(args.query, args.radius)

    os.makedirs(args.output_dir, exist_ok=True)
    from slugify import slugify
    hotel_slug = args.hotel.replace(" ", "-").lower()
    query_slug = args.query[:20].replace(" ", "-").lower()

    md_path = os.path.join(args.output_dir, f"{hotel_slug}-{query_slug}.md")
    html_path = os.path.join(args.output_dir, f"{hotel_slug}-{query_slug}.html")

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md)
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"\n✅ 报告生成完成!")
    print(f"   Markdown: {md_path}")
    print(f"   HTML: {html_path}")
    print(f"\n📝 预览:")
    print("-" * 60)
    print(md)


if __name__ == "__main__":
    main()
